@startuml

title
cd RobotInterface
end title

:<<external>> \n MotionPlanner:

rectangle "<<subsystem>> \n InterfaceSystem" as (IS){

    component RobotInterface{
        component "High level" as HL
        component "Low level" as LL
        interface "Lowlevel driver" as l
    }

    'Interface Position
    () "<<ros::action>> \n Position" as Position
    () "<<ros::service>> \n Emergency break" as ebs
    :<<external>> \n MotionPlanner: -right--( Position
    :<<external>> \n MotionPlanner: -right--( ebs
    HL -right-( l
    l -right- LL
    Position -left- HL
    ebs -up- HL
}

rectangle "<<subsystem>> \n SSC-32U" as (RA){

    component "SSC-32U" as SC
    interface "SSC-32U command" as CMD

    'Interface CMD
    LL #-down--( CMD : <<USB>>
    CMD -down--# SC
}

rectangle "<<subsystem>> \n Lyxnmotion AL5D" as (LM){

    component "Lyxnmotion AL5D servos" as RS
    interface PWMSignal

    'Interface PWMSignal
    SC #-right--( PWMSignal : <<jumper cables>>
    PWMSignal -right--# RS
}
@enduml