// Auto-generated. Do not edit!

// (in-package robot_interface.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class PositionResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.executionTime = null;
      this.successFull = null;
    }
    else {
      if (initObj.hasOwnProperty('executionTime')) {
        this.executionTime = initObj.executionTime
      }
      else {
        this.executionTime = 0;
      }
      if (initObj.hasOwnProperty('successFull')) {
        this.successFull = initObj.successFull
      }
      else {
        this.successFull = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type PositionResult
    // Serialize message field [executionTime]
    bufferOffset = _serializer.uint64(obj.executionTime, buffer, bufferOffset);
    // Serialize message field [successFull]
    bufferOffset = _serializer.bool(obj.successFull, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type PositionResult
    let len;
    let data = new PositionResult(null);
    // Deserialize message field [executionTime]
    data.executionTime = _deserializer.uint64(buffer, bufferOffset);
    // Deserialize message field [successFull]
    data.successFull = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 9;
  }

  static datatype() {
    // Returns string type for a message object
    return 'robot_interface/PositionResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'cd5dc94f615bfbb507638cfc171ea7a0';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    uint64 executionTime
    bool   successFull
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new PositionResult(null);
    if (msg.executionTime !== undefined) {
      resolved.executionTime = msg.executionTime;
    }
    else {
      resolved.executionTime = 0
    }

    if (msg.successFull !== undefined) {
      resolved.successFull = msg.successFull;
    }
    else {
      resolved.successFull = false
    }

    return resolved;
    }
};

module.exports = PositionResult;
