// Generated by gencpp from file robot_interface/EmergencyStopRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_INTERFACE_MESSAGE_EMERGENCYSTOPREQUEST_H
#define ROBOT_INTERFACE_MESSAGE_EMERGENCYSTOPREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_interface
{
template <class ContainerAllocator>
struct EmergencyStopRequest_
{
  typedef EmergencyStopRequest_<ContainerAllocator> Type;

  EmergencyStopRequest_()
    : stop(false)  {
    }
  EmergencyStopRequest_(const ContainerAllocator& _alloc)
    : stop(false)  {
  (void)_alloc;
    }



   typedef uint8_t _stop_type;
  _stop_type stop;





  typedef boost::shared_ptr< ::robot_interface::EmergencyStopRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_interface::EmergencyStopRequest_<ContainerAllocator> const> ConstPtr;

}; // struct EmergencyStopRequest_

typedef ::robot_interface::EmergencyStopRequest_<std::allocator<void> > EmergencyStopRequest;

typedef boost::shared_ptr< ::robot_interface::EmergencyStopRequest > EmergencyStopRequestPtr;
typedef boost::shared_ptr< ::robot_interface::EmergencyStopRequest const> EmergencyStopRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_interface::EmergencyStopRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_interface::EmergencyStopRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_interface

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/lunar/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg'], 'robot_interface': ['/home/ties/Documents/WorldOfRobots/World/world-beroepsproduct1/world_ws/devel/share/robot_interface/msg', '/home/ties/Documents/WorldOfRobots/World/world-beroepsproduct1/world_ws/src/robot_interface/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_interface::EmergencyStopRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_interface::EmergencyStopRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_interface::EmergencyStopRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_interface::EmergencyStopRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_interface::EmergencyStopRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_interface::EmergencyStopRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_interface::EmergencyStopRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "71f1172402e56b82716ca71681cded6b";
  }

  static const char* value(const ::robot_interface::EmergencyStopRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x71f1172402e56b82ULL;
  static const uint64_t static_value2 = 0x716ca71681cded6bULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_interface::EmergencyStopRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_interface/EmergencyStopRequest";
  }

  static const char* value(const ::robot_interface::EmergencyStopRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_interface::EmergencyStopRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool stop\n\
";
  }

  static const char* value(const ::robot_interface::EmergencyStopRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_interface::EmergencyStopRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stop);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EmergencyStopRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_interface::EmergencyStopRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_interface::EmergencyStopRequest_<ContainerAllocator>& v)
  {
    s << indent << "stop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.stop);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_INTERFACE_MESSAGE_EMERGENCYSTOPREQUEST_H
