// Generated by gencpp from file robot_interface/PositionResult.msg
// DO NOT EDIT!


#ifndef ROBOT_INTERFACE_MESSAGE_POSITIONRESULT_H
#define ROBOT_INTERFACE_MESSAGE_POSITIONRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_interface
{
template <class ContainerAllocator>
struct PositionResult_
{
  typedef PositionResult_<ContainerAllocator> Type;

  PositionResult_()
    : executionTime(0)
    , successFull(false)  {
    }
  PositionResult_(const ContainerAllocator& _alloc)
    : executionTime(0)
    , successFull(false)  {
  (void)_alloc;
    }



   typedef uint64_t _executionTime_type;
  _executionTime_type executionTime;

   typedef uint8_t _successFull_type;
  _successFull_type successFull;





  typedef boost::shared_ptr< ::robot_interface::PositionResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_interface::PositionResult_<ContainerAllocator> const> ConstPtr;

}; // struct PositionResult_

typedef ::robot_interface::PositionResult_<std::allocator<void> > PositionResult;

typedef boost::shared_ptr< ::robot_interface::PositionResult > PositionResultPtr;
typedef boost::shared_ptr< ::robot_interface::PositionResult const> PositionResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_interface::PositionResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_interface::PositionResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_interface

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/lunar/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg'], 'robot_interface': ['/home/ties/Documents/WorldOfRobots/World/world-beroepsproduct1/world_ws/devel/share/robot_interface/msg', '/home/ties/Documents/WorldOfRobots/World/world-beroepsproduct1/world_ws/src/robot_interface/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_interface::PositionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_interface::PositionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_interface::PositionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_interface::PositionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_interface::PositionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_interface::PositionResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_interface::PositionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cd5dc94f615bfbb507638cfc171ea7a0";
  }

  static const char* value(const ::robot_interface::PositionResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcd5dc94f615bfbb5ULL;
  static const uint64_t static_value2 = 0x07638cfc171ea7a0ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_interface::PositionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_interface/PositionResult";
  }

  static const char* value(const ::robot_interface::PositionResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_interface::PositionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
uint64 executionTime\n\
bool   successFull\n\
";
  }

  static const char* value(const ::robot_interface::PositionResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_interface::PositionResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.executionTime);
      stream.next(m.successFull);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PositionResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_interface::PositionResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_interface::PositionResult_<ContainerAllocator>& v)
  {
    s << indent << "executionTime: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.executionTime);
    s << indent << "successFull: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.successFull);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_INTERFACE_MESSAGE_POSITIONRESULT_H
