(cl:defpackage robot_interface-msg
  (:use )
  (:export
   "<ANGLE>"
   "ANGLE"
   "<CONFIGURATION>"
   "CONFIGURATION"
   "<POSITIONACTION>"
   "POSITIONACTION"
   "<POSITIONACTIONFEEDBACK>"
   "POSITIONACTIONFEEDBACK"
   "<POSITIONACTIONGOAL>"
   "POSITIONACTIONGOAL"
   "<POSITIONACTIONRESULT>"
   "POSITIONACTIONRESULT"
   "<POSITIONFEEDBACK>"
   "POSITIONFEEDBACK"
   "<POSITIONGOAL>"
   "POSITIONGOAL"
   "<POSITIONRESULT>"
   "POSITIONRESULT"
  ))

