; Auto-generated. Do not edit!


(cl:in-package robot_interface-msg)


;//! \htmlinclude PositionResult.msg.html

(cl:defclass <PositionResult> (roslisp-msg-protocol:ros-message)
  ((executionTime
    :reader executionTime
    :initarg :executionTime
    :type cl:integer
    :initform 0)
   (successFull
    :reader successFull
    :initarg :successFull
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass PositionResult (<PositionResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PositionResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PositionResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot_interface-msg:<PositionResult> is deprecated: use robot_interface-msg:PositionResult instead.")))

(cl:ensure-generic-function 'executionTime-val :lambda-list '(m))
(cl:defmethod executionTime-val ((m <PositionResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_interface-msg:executionTime-val is deprecated.  Use robot_interface-msg:executionTime instead.")
  (executionTime m))

(cl:ensure-generic-function 'successFull-val :lambda-list '(m))
(cl:defmethod successFull-val ((m <PositionResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_interface-msg:successFull-val is deprecated.  Use robot_interface-msg:successFull instead.")
  (successFull m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PositionResult>) ostream)
  "Serializes a message object of type '<PositionResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'executionTime)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'executionTime)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'executionTime)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'executionTime)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 32) (cl:slot-value msg 'executionTime)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 40) (cl:slot-value msg 'executionTime)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 48) (cl:slot-value msg 'executionTime)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 56) (cl:slot-value msg 'executionTime)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'successFull) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PositionResult>) istream)
  "Deserializes a message object of type '<PositionResult>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'executionTime)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'executionTime)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'executionTime)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'executionTime)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 32) (cl:slot-value msg 'executionTime)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 40) (cl:slot-value msg 'executionTime)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 48) (cl:slot-value msg 'executionTime)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 56) (cl:slot-value msg 'executionTime)) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'successFull) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PositionResult>)))
  "Returns string type for a message object of type '<PositionResult>"
  "robot_interface/PositionResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PositionResult)))
  "Returns string type for a message object of type 'PositionResult"
  "robot_interface/PositionResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PositionResult>)))
  "Returns md5sum for a message object of type '<PositionResult>"
  "cd5dc94f615bfbb507638cfc171ea7a0")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PositionResult)))
  "Returns md5sum for a message object of type 'PositionResult"
  "cd5dc94f615bfbb507638cfc171ea7a0")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PositionResult>)))
  "Returns full string definition for message of type '<PositionResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint64 executionTime~%bool   successFull~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PositionResult)))
  "Returns full string definition for message of type 'PositionResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint64 executionTime~%bool   successFull~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PositionResult>))
  (cl:+ 0
     8
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PositionResult>))
  "Converts a ROS message object to a list"
  (cl:list 'PositionResult
    (cl:cons ':executionTime (executionTime msg))
    (cl:cons ':successFull (successFull msg))
))
